---
title: "Simulating a Gaussian State-Space Model"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{my-vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


```{r setup}
#library(genss)
```

```{r}
#library(pomp)
#library(genss)

# this will probably become a vignette at some point

# my_data <- diag(1, 10, 3)
# 
# # discrete time grm
# loadings_mat <- matrix(data = c(c(1, 0), c(1, 0), c(1, 0)), nrow = 3, ncol = 2, byrow = TRUE)
# alphas <- c(1, 1, 1)
# betas <- list(
#   c(-2, -1, 0, 1),
#   c(-1.5, -.5, .5, 1.5),
#   c(-2.5, -1.5, -.5, .5)
# )
# 
# process_mat <- matrix(data = c(c(.5, .6), c(.7, .8)), nrow = 2, ncol = 2)
# 
# grm_discrete <- grm_two_state_statespacemodel(n_measures=NROW(loadings_mat),
#                               process_mat=process_mat,
#                               loadings_mat = loadings_mat,
#                               alphas=alphas,
#                               betas=betas,
#                               times=1:100,
#                               sim=TRUE)
# 
# plot(simulate(grm_discrete))
# spy(grm_discrete)
# 
# 
# 
# # discrete time lin
# loadings_mat <- matrix(data = c(c(1, 0), c(0, 1), c(1, 0)), nrow = 3, ncol = 2, byrow = TRUE)
# process_mat <- matrix(data = c(c(.7, .3), c(.2, .1)), nrow = 2, ncol = 2)
# sigmas <- c(5, 1, 1)
# 
# test <- lin_two_state_statespacemodel(
#                               n_measures=NROW(loadings_mat),
#                               process_mat=process_mat,
#                               loadings_mat = loadings_mat,
#                               sigmas=sigmas,
#                               times=1:100,
#                               sim=TRUE)
# plot(simulate(test))
```
